import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";

const beVietnamProSans = Be_Vietnam_Pro({
  variable: "--font-be-vietnam-pro-sans",
  subsets: ["latin"],
  weight: ['100','200','300','400','500','600','700','800','900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${beVietnamProSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
